### ISSUE TITLE
Test does not pass

### ISSUE THREAD

**Issue by benmwebb** [3DGenomes/IMP_BioSystem_Domain_Fly_Genome#1]
With IMP 2.6.2, with the test modified to use `--ncpus 1` (rather the default 12, as I have a slow test machine) the test does not pass:

```
$ python test.py
...
   xx    0.9       0     900   0.01       2  0.2888
   xx    1.2    -1.2     900   0.01       2  0.2794
   xx    1.2    -0.9     900   0.01       2  0.2867
   xx    1.2    -0.6     900   0.01       2  0.2921
   xx    1.2    -0.3     900   0.01       2  0.2883
   xx    1.2       0     900   0.01       2  0.286
                Optimal values: scale:0.01 maxdist:300.0 upper:0.0 lower:-0.6 dcutoff:2.0 with cc: 0.8244
        Modeling (this can take long)...
# Harmonic      part1   part2   dist    kforce

date
                Writing models, list and chimera files...
F
======================================================================
FAIL: test_1_3d_modelling_optimization (__main__.TestTadbit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 40, in test_1_3d_modelling_optimization
    self.assertEqual(sha, correct_sha)
AssertionError: '4491f9cb-9dbf-5e96-96c6-aa3fc743d836' != '0b42fb54-7188-5b47-a922-63b5db43ae42'
```

The test isn't comparing for exact equality of floating point values (or something like that) is it?

**Comment by david-castillo** [comment]
Yes, we have to change the test result. The hash is indeed coming from an ensemble of floating points and that is processor specific.
Let us think about what to test and we will modify the code. Any suggestion?

**Comment by benmwebb** [comment]
I'm not familiar enough with your algorithm to give any _useful_ suggestions, but in cases where we're comparing a single score evaluation, a "nearly equal" rather than "exactly equal" test works fine on each component (in Python unittest, `assertAlmostEqual(value, expected, delta)`). For a complete sampling run, small processor-specific rounding differences are going to accumulate during the run so your final configurations may differ wildly between machines, so that won't work. In that case we test to see if the test ensemble (rather than a single configuration) is close to the "known good" ensemble, e.g. by clustering and comparing cluster centers. But this may be impractical depending on how much of the conformational space you can cover in your test run.

**Comment by david-castillo** [comment]
I've changed the test to a more qualitative approach.
Now we compare a contact matrix build from the obtained models with the original data use to build them. We expect a high correlation score otherwise something is wrong.
Can you check if you pass the test now?

**Comment by benmwebb** [comment]
Yes, the test passes now on my machine, thanks!
